services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 3000:3000
